version: '3.9'

services:

  api:
    image: sergoja/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: always

  migrations:
    image: sergoja/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate

  postgres:
    image: postgres:latest
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  front:
    image: sermalenk/skypro-front:lesson-37
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    restart: always

  bot:
    image: sergoja/todolist:latest
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: python3 manage.py runbot