# Generated by Django 4.2.2 on 2023-07-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Пользователь'), ('admin', 'Админ')], default='member', max_length=10),
        ),
    ]
