# Generated by Django 4.2.2 on 2023-08-16 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='user_ud',
        ),
        migrations.AddField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Chat ID'),
        ),
    ]
